name: Backend

on: [workflow_dispatch, push, pull_request]

jobs:
  run:
    uses: flarum/framework/.github/workflows/REUSABLE_backend.yml@main
    with:
      enable_backend_testing: true
      enable_phpstan: true

      backend_directory: .
      php_versions: '["8.1", "8.2", "8.3"]'
      db_versions: '["mysql:5.7", "mariadb:10.4"]'
